

# Snowflake credentials
account = "ts33775.ap-southeast-1"
user = "VIJAYTDESHMUKH"
password = "Vijaytdeshmukh@4513"
warehouse = "COMPUTE_WH"
database = "NEXUS"
schema = "ATTENDENCE"
client_session_keep_alive = true

# AWS credentials
access_key = "AKIAQ4NXQIPEO72GZHEK"
secret_key = "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"
region = "ap-southeast-1"
